### ISSUE TITLE
NPC's opinions change if you keep clicking on them

### ISSUE THREAD

**Issue by tsmale** [royletron/dungeon-advisor#18]
This is because it's cycling through their list of opinions but it looks as if it's being randomised every time

![screen shot 2015-09-04 at 15 35 38](https://cloud.githubusercontent.com/assets/13199274/9686218/cd99d488-531a-11e5-8329-2c202bbe9925.png)
![screen shot 2015-09-04 at 15 36 38](https://cloud.githubusercontent.com/assets/13199274/9686219/cdb0be00-531a-11e5-8af5-234336a4d4f2.png)
![screen shot 2015-09-04 at 15 35 53](https://cloud.githubusercontent.com/assets/13199274/9686220/cdbf31ce-531a-11e5-90f8-cd76f73b115a.png)

**Comment by royletron** [comment]
Not sure I am going to sort this one out, it is a pain to fix and is quite useful....
